config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers:
      { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'home#index'

  get '/oauth_failure' => 'login#oauth_failure'
  get 'imprint' => 'pages#imprint', as: 'imprint'
  get 'help' => 'pages#help', as: 'help'
  get 'health' => 'health#index', as: 'health'

  resource :home, controller: :home, only: :index
  get 'search/', to: 'search#show', as: :empty_search
  get 'search/:query', to: 'search#show', as: :search
  resources :songs, only: %i[show update]
  get ':username', to: 'users#show', as: :user
  get ':username/:id', to: 'songs#show', as: :user_song
  resources :notebooks, only: %i[new create update destroy]
end

app/models/notebook.rb
# frozen_string_literal: true

class Notebook < ApplicationRecord
  belongs_to :user
  has_many :songs, dependent: :destroy
end

app/controllers/notebooks_controller.rb
# frozen_string_literal: true

class NotebooksController < ApplicationController
  before_action :load_resource, only: %i[update destroy]
  before_action :authenticate_user!, only: %i[update destroy]

  def new
    @notebook = Notebook.new
    @evernote_notebooks = evernote_notebook_collection
  end

  def create
    @notebook = notebooks.create(permitted_params)
    UpdateNotebook.call(notebook: @notebook)

    redirect_to(root_path,
                notice: "Notebook \"#{@notebook.name}\" succesfully created")
  end

  def update
    if UpdateNotebook.call(notebook: @notebook).success?
      redirect_to(root_path,
                  notice: "Notebook \"#{@notebook.name}\" succesfully updated")
    else
      redirect_to(root_path,
                  alert: "Notebook \"#{@notebook.name}\" not updated")
    end
  end

  def destroy
    if @notebook.destroy
      redirect_to(root_path,
                  notice: "Notebook \"#{@notebook.name}\" succesfully created")
    else
      redirect_to(root_path,
                  alert: "Notebook \"#{@notebook.name}\" could not be deleted")
    end
  end

  private

  def load_resource
    @notebook = Notebook.find(params[:id])
  end

  def evernote_notebook_collection
    evernote_service.notebook_names.reject { |name| name.in?(notebook_names) }
  end

  def notebook_names
    notebooks.map(&:name)
  end

  def notebooks
    current_user.notebooks
  end

  def permitted_params
    params.require(:notebook).permit(:name)
  end
end

app/views/notebooks/_add_first.html.haml
%h3.ui.header Add your song notebook
%p Have all of your songs collected in one Evernote Notebook and add this notebook here.
= link_to t('.add_notebook'), '#', class: 'ui huge button primary addNotebook'

= render 'notebooks/form_modal', notebook: @notebook, evernote_notebooks: @evernote_notebooks

app/views/notebooks/_form.html.haml
= form_for notebook, html: { class: 'form ui' } do |f|
  .field
    = f.label :name, 'Which Notebook contains your songs?'
    = f.select :name, options_for_select(evernote_notebooks), class: 'dropdown'
  .field
    = f.submit("Add Notebook", class: 'ui submit button')

app/views/notebooks/_form_modal.html.haml
.ui.modal.addNotebook

  %i.close.icon
  .header
    Add Evernote Notebook
  .content
    = form_for notebook, html: { class: 'form ui' } do |f|
      .field
        = f.label :name, 'Which Notebook contains your songs?'
        = f.select :name, options_for_select(evernote_notebooks), class: 'dropdown'
      .field
        = f.submit("Add Notebook", class: 'ui submit button')

app/views/notebooks/_list.html.haml
= turbo_frame_tag 'notebooks' do
  .ui.top.attached.tabular.menu.notebooks
    - current_user.notebooks.each_with_index do |notebook, index|
      = link_to '#', class: "notebook item #{'active' if index.zero?}", data: { tab: notebook.name.underscore } do
        = "#{notebook.name} (#{notebook.songs.count})"
    .right.menu
      .item
        = link_to t('.add_notebook'), '#', class: 'ui button addNotebook'

  - current_user.notebooks.each_with_index do |notebook, index|
    .ui.bottom.attached.tab.segment{ data: { tab: notebook.name.underscore }, class: "#{'active' if index.zero?}" }
      = turbo_frame_tag notebook do
        = render 'notebooks/notebook', notebook: notebook

= render 'notebooks/form_modal', notebook: @notebook, evernote_notebooks: @evernote_notebooks

app/views/notebooks/_notebook.html.haml
%table.ui.very.basic.table.unstackable
  %thead
    %tr
      %th= t('.title')
      %th= t('.album')
      %th= t('.access')
      %th= t('.date')
  %tbody
    - notebook.songs.by_title.each do |song|
      %tr
        %td
          = link_to user_song_path(song.user, song), 'data-turbo-frame' => '_top' do
            %i.icon.music
            = song.title
        %td.collapsing
          = song.album
        %td.collapsing
          - if song.published?
            %i.icon.eye
          - elsif song.restricted?
            %i.icon.ban
          - else
            %i.icon.eye.slash
        %td.collapsing
          = song.updated_at.to_date
  %tfoot.full-width
    %tr
      %th{colspan: "4"}
        = link_to notebook_path(notebook), 'data-turbo-method' => :put, class: 'ui small basic button' do
          %i.icon.refresh
          = t('.refresh')
        = link_to notebook_path(notebook), 'data-turbo-method' => :delete, class: 'ui small basic button' do
          %i.icon.close
          = t('.delete')

app/views/notebooks/create.turbostream.erb
<%= turbo_stream.replace 'notebooks', partial: 'notebooks/list' %>

app/views/notebooks/destroy.turbostream.erb
<%= turbo_stream.replace 'notebooks', partial: 'notebooks/list' %>

app/views/notebooks/new.html.haml
- content_for :meta do
  %title Add Notebook - Everchords

.ui.text.container
  = render 'form', notebook: @notebook, evernote_notebooks: @evernote_notebooks

app/views/notebooks/update.turbostream.erb
<%= turbo_stream.replace @notebook %>