config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers:
      { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'home#index'

  get '/oauth_failure' => 'login#oauth_failure'
  get 'imprint' => 'pages#imprint', as: 'imprint'
  get 'help' => 'pages#help', as: 'help'
  get 'health' => 'health#index', as: 'health'

  resource :home, controller: :home, only: :index
  get 'search/', to: 'search#show', as: :empty_search
  get 'search/:query', to: 'search#show', as: :search
  resources :songs, only: %i[show update]
  get ':username', to: 'users#show', as: :user
  get ':username/:id', to: 'songs#show', as: :user_song
  resources :notebooks, only: %i[new create update destroy]
end

app/views/shared/_3_steps.html.haml
.ui.steps
  .step{ class: "#{'active' if step == 0} #{'disabled' if step > 0}"}
    %i.sign.in.alternate.icon
    .content
      .title Connect
      .description with your Evernote
  .step{ class: "#{'active' if step == 1} #{'disabled' if step > 1}"}
    %i.book.icon
    .content
      .title Permit
      .description access to your notebooks
  .step
    %i.music.icon
    .content
      .title Display
      .description your lyrics beautifully

app/views/shared/_footer.html.haml
.ui.vertical.footer.segment
  .ui.center.aligned.container
    .ui.inverted.section.divider

    = image_tag 'favicons/favicon-32x32.png', class: 'ui centered mini image'
    .ui.horizontal.small.divided.link.list
      = link_to t('.help'), help_path, class: 'item'
      = mail_to 'public+everchords@danielsenff.de', t('.contact'), class: 'item'
      = link_to t('.legal'), imprint_path, class: 'item'
      - if can?(:read, :dashboard)
        = link_to 'Admin', rails_admin_path, class: 'item'
  .ui.center.aligned.container
    .ui.inverted.section.divider
    .ui.horizontal.small.divided.link.list
      Everchords is a project by
      = link_to 'Daniel Senff', 'http://www.danielsenff.de'
      %br
      = link_to 'Follow on Twitter', 'https://www.twitter.com/dahie'

app/views/shared/_fretboard.html.haml
.ui.container
  .ui.styled.fluid.accordion
    .title.chord-diagrams
      %i.dropdown.icon
      Chord Diagrams
    .content.chord-diagrams
      - @song.chords.each do |chord|
        = link_to "https://ukebuddy.com/ukulele-chords/#{chord}-chord", target: :blank do
          = raw(ChordDiagrams.ukulele_svg(chord.sub('maj', 'M')))
    - @fretboards.each do |fretboard|
      .title{class: fretboard.name.parameterize}
        %i.dropdown.icon
        = fretboard.name
        fretboard
      .content{class: fretboard.name.parameterize}
        %table.ui.very.basic.collapsing.celled.table.fretboard
          %tbody
            - fretboard.strings.each do |string|
              %tr
                - fretboard.fret_count.times do |index|
                  - note = Coltrane::Theory::Note[string] + index
                  %td{ class: "fret-#{index} #{'striped' if fretboard.any_dots_at?(index) }" }
                    = note.pretty_name
            %tr.markers
              - fretboard.fret_count.times do |index|
                %td{ class: "fret-#{index} #{'striped' if fretboard.any_dots_at?(index) }" }
                  - if fretboard.double_dots_at?(index)
                    %i.icon.circle
                    %i.icon.circle
                  - elsif fretboard.single_dot_at?(index)
                    %i.icon.circle

app/views/shared/_meta.html.haml
= csrf_meta_tags

= stylesheet_link_tag "application", "data-turbo-track": "reload"
%link{ href: image_path("favicons/apple-icon-57x57.png"), rel: "apple-touch-icon", sizes: "57x57" }
%link{ href: image_path("favicons/apple-icon-60x60.png"), rel: "apple-touch-icon", sizes: "60x60" }
%link{ href: image_path("favicons/apple-icon-72x72.png"), rel: "apple-touch-icon", sizes: "72x72" }
%link{ href: image_path("favicons/apple-icon-76x76.png"), rel: "apple-touch-icon", sizes: "76x76" }
%link{ href: image_path("favicons/apple-icon-114x114.png"), rel: "apple-touch-icon", sizes: "114x114" }
%link{ href: image_path("favicons/apple-icon-120x120.png"), rel: "apple-touch-icon", sizes: "120x120" }
%link{ href: image_path("favicons/apple-icon-144x144.png"), rel: "apple-touch-icon", sizes: "144x144" }
%link{ href: image_path("favicons/apple-icon-152x152.png"), rel: "apple-touch-icon", sizes: "152x152" }
%link{ href: image_path("favicons/apple-icon-180x180.png"), rel: "apple-touch-icon", sizes: "180x180" }
%link{ href: image_path("favicons/android-icon-192x192.png"), rel: "icon", sizes: "192x192", type: "image/png" }
%link{ href: image_path("favicons/favicon-32x32.png"), rel:  "icon", sizes: "32x32", type: "image/png"}
%link{ href: image_path("favicons/favicon-96x96.png"), rel:  "icon", sizes: "96x96", type: "image/png"}
%link{ href: image_path("favicons/favicon-16x16.png"), rel:  "icon", sizes: "16x16", type: "image/png"}
%link{ href: image_path("favicons/manifest.json"), rel: "manifest" }
%meta{content: "#ffffff", name: "msapplication-TileColor" }
%meta{content: image_path("favicons/ms-icon-144x144.png"), name: "msapplication-TileImage" }
%meta{content: "#ffffff", name: "theme-color" }

%meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" }

%meta{content: "songpro, chordpro, lyrics, chords, tabs, guitar, ukulele, evernote", name: "keywords"}
%meta{content: "index, follow", name: "robots"}
%meta{content: "EN", name: "language"}
%meta{content: "Daniel Senff", name: "author"}
%meta{content: "global", name: "distribution"}

%meta{:content => "Everchords - Share your song lyrics beautifully", :name => "title"}/
%meta{:content => "With Everchords, you can display your lyrics in a compact, beautiful way. Share your songs online in an easy way for others to read, play along and print. ", :name => "description"}/
/ Open Graph / Facebook
%meta{:content => "website", :property => "og:type"}/
%meta{:content => "https://everchords.herokuapp.com/", :property => "og:url"}/
%meta{:content => "Everchords - Share your song lyrics beautifully", :property => "og:title"}/
%meta{:content => "With Everchords, you can display your lyrics in a compact, beautiful way. Share your songs online in an easy way for others to read, play along and print. ", :property => "og:description"}/
%meta{content: image_path("social.jpg"), :property => "og:image"}/
/ Twitter
%meta{:content => "summary_large_image", :property => "twitter:card"}/
%meta{:content => "https://everchords.herokuapp.com/", :property => "twitter:url"}/
%meta{:content => "Everchords - Share your song lyrics beautifully", :property => "twitter:title"}/
%meta{:content => "With Everchords, you can display your lyrics in a compact, beautiful way. Share your songs online in an easy way for others to read, play along and print. ", :property => "twitter:description"}/
%meta{content: image_path("social.jpg"), property: "twitter:image"}/


= yield :meta

app/views/shared/_navigation.html.haml
.ui.container.top.attached
  = link_to root_path, class: 'item header ' do
    = image_tag 'favicons/favicon-32x32.png'
    - unless @song
      %span.title Everchords

  - if @song
    .ui.simple.dropdown.item
      = @song.notebook.name
      %i.icon.dropdown
      .menu.notebooks
        - if @song.user == current_user
          - @song.notebook.songs.by_title.each do |song|
            .item
              = link_to song.title, user_song_path(current_user, song)

    .ui.simple.dropdown.item
      = @song.title
      %i.icon.dropdown
      .menu
        .item
          Key:
          %strong
            - if @song.key
              = link_to @song.key, @song.key_url, target: :blank
            - else
              = '-'
          - if @song.capo
            Capo:
            %strong
              = @song.capo
          Speed:
          %strong
            = @song.tempo && "#{@song.tempo}bpm" || '-'
        .item
          Chords:
          - @song.chords.each do |chord|
            %a{ tabindex: "0", role:"button", data: { html: "true", placement: 'bottom'} }
            %kbd= chord
        - if @song.capo
          .item
            Capo:
            %kbd= @song.capo
        - if @song.user == current_user
          .item
            = link_to song_path(@song), 'data-turbo-method' => :put do
              %i.refresh.icon
              Refresh
          - if current_user.admin?
            .item
              = link_to '#', class: 'openDebugInfo' do
                %i.bug.icon
                Debug
          .item
            = link_to @song.evernote_url, target: :blank do
              %i.icon.external.alternate
              = t('.open_with_evernote')
          .item
            .ui.action.input{'data-controller' => 'clipboard' }
              = text_field_tag(:url, request.base_url + @song.share_url,  id: 'shareSongUrl', readonly: true, autofocus: true, 'data-clipboard-target' => "source" )
              = button_tag(class: "ui button right icon", 'data-action' => "clipboard#copy") do 
                %i.copy.icon

  - if current_user.present?
    .right.menu
      .ui.simple.right.item.search
        .ui.transparent.icon.input
          %input.prompt{ type: "text", placeholder: "Search …", accesskey: 't' }
            %i.search.icon
          

      .ui.simple.right.dropdown.item
        = current_user.username
        %i.dropdown.icon
        .more.menu
          = link_to t('.profile'), user_path(current_user), class: 'item'
          = link_to t('.songbooks'), root_path, class: 'item'
          = link_to t('.logout'), destroy_user_session_path, class: 'item'
    .results
  - else
    = link_to t('.about_us'), help_path, class: 'ui simple item'
    = link_to t('.login_with_evernote', provider: t("omniauth.providers.evernote")), user_evernote_omniauth_authorize_path, class: 'ui button inverted', 'turbo-method' => :post